server:
  port: ${PORT:2333}
  address: 0.0.0.0
  http2:
    enabled: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      snapshot: false

  pluginsDir: "./plugins"
  defaultPluginRepository: "https://maven.lavalink.dev/releases"

  server:
    password: "${LAVALINK_SERVER_PASSWORD}"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      nico: false
      http: false
      local: false

    filters:
      volume: true
      equalizer: false
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false

    nonAllocatingFrameBuffer: false
    bufferDurationMs: 200
    frameBufferDurationMs: 3000
    opusEncodingQuality: 5
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 3
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: false
    soundcloudFilterOutPreviewTracks: false
    gc-warnings: false

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file:
    path: ./logs/

  level:
    root: WARN
    lavalink: INFO

  request:
    enabled: false

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 2
